project:
  type: website
  output-dir: docs

website:
  title: "Rstudio Scripts"
  navbar:
    left:
    - href: index.qmd
      text: Inici
    - href: basics.qmd
      text: Basics
    - href: estadistica.qmd
      text: Estadística
    - text: Gràfics
      menu:
        - href: grafics.qmd
          text: Introducció
        - href: pcr.qmd
          text: Gràfic de punts (PCR)
        - href: elisa.qmd
          text: Gràfic de barres (ELISA)
        - href: heatmap.qmd
          text: Heatmap
        - href: correlation.qmd
          text: Heatmap correlations
        - href: extra.qmd
          text: Dumpster
    - href: quarto.qmd
      text: Quarto
    - href: final.qmd
      text: Final

format:
  html:
    toc: true
    toc-depth: 3

